// QuantPilot AI – Erweiterte Mock-Daten für ARB-Scan, Runner-Protection & Reverse-Short
// In Produktion: Anbindung an FastAPI-Backend + CCXT + InfluxDB

// ─── ARB-Scan ──────────────────────────────────────────────────────
export const arbOpportunities = [
  {
    id: "arb_001",
    symbol: "BTCUSDT",
    buy_exchange: "MEXC",
    sell_exchange: "BINANCE",
    buy_price: 61180.5,
    sell_price: 61250.5,
    raw_spread_percent: 0.114,
    taker_fee_percent: 0.08,
    estimated_slippage_percent: 0.015,
    funding_cost_percent: 0.005,
    net_profit_percent: 0.014,
    market_regime: "CALM",
    is_profitable_after_costs: true,
    telegram_alert_sent: true,
    governance_approved: false,
    status: "ALERTED",
    notes: "Netto-Chance nach Gebühren – Governance-Freigabe ausstehend",
    created_date: "2026-07-09T14:28:00Z",
  },
  {
    id: "arb_002",
    symbol: "ETHUSDT",
    buy_exchange: "BINANCE",
    sell_exchange: "OKX",
    buy_price: 3140.2,
    sell_price: 3148.8,
    raw_spread_percent: 0.274,
    taker_fee_percent: 0.10,
    estimated_slippage_percent: 0.03,
    funding_cost_percent: 0.008,
    net_profit_percent: 0.136,
    market_regime: "TRENDING",
    is_profitable_after_costs: true,
    telegram_alert_sent: true,
    governance_approved: false,
    status: "GOVERNANCE_PENDING",
    notes: "Spread > 0.2% – wirtschaftlich relevant",
    created_date: "2026-07-09T14:15:00Z",
  },
  {
    id: "arb_003",
    symbol: "SOLUSDT",
    buy_exchange: "BYBIT",
    sell_exchange: "MEXC",
    buy_price: 147.9,
    sell_price: 148.1,
    raw_spread_percent: 0.135,
    taker_fee_percent: 0.10,
    estimated_slippage_percent: 0.04,
    funding_cost_percent: 0.003,
    net_profit_percent: -0.008,
    market_regime: "VOLATILE",
    is_profitable_after_costs: false,
    telegram_alert_sent: false,
    governance_approved: false,
    status: "DETECTED",
    notes: "Nach Kosten nicht profitabel – keine Alert",
    created_date: "2026-07-09T13:50:00Z",
  },
  {
    id: "arb_004",
    symbol: "XRPUSDT",
    buy_exchange: "MEXC",
    sell_exchange: "BINANCE",
    buy_price: 0.6238,
    sell_price: 0.6265,
    raw_spread_percent: 0.433,
    taker_fee_percent: 0.08,
    estimated_slippage_percent: 0.02,
    funding_cost_percent: 0.002,
    net_profit_percent: 0.331,
    market_regime: "TRENDING",
    is_profitable_after_costs: true,
    telegram_alert_sent: true,
    governance_approved: true,
    status: "APPROVED",
    notes: "Starke Chance – Governance freigegeben, Paper-Ausführung bereit",
    created_date: "2026-07-09T13:20:00Z",
  },
  {
    id: "arb_005",
    symbol: "DOGEUSDT",
    buy_exchange: "OKX",
    sell_exchange: "BYBIT",
    buy_price: 0.1238,
    sell_price: 0.1240,
    raw_spread_percent: 0.162,
    taker_fee_percent: 0.10,
    estimated_slippage_percent: 0.06,
    funding_cost_percent: 0.004,
    net_profit_percent: -0.002,
    market_regime: "ILLIQUID",
    is_profitable_after_costs: false,
    telegram_alert_sent: false,
    governance_approved: false,
    status: "EXPIRED",
    notes: "Illiquider Markt – Slippage zu hoch",
    created_date: "2026-07-09T12:10:00Z",
  },
];

export const arbRegimeStats = {
  CALM: { count: 12, avg_spread: 0.08, profitable: 3 },
  VOLATILE: { count: 8, avg_spread: 0.18, profitable: 2 },
  TRENDING: { count: 15, avg_spread: 0.22, profitable: 5 },
  ILLIQUID: { count: 4, avg_spread: 0.31, profitable: 0 },
  EXTREME: { count: 2, avg_spread: 0.45, profitable: 1 },
};

export const arbExchangeStatus = [
  { exchange: "BINANCE", status: "CONNECTED", latency_ms: 42, symbols_scanned: 180, rate_limit_percent: 68 },
  { exchange: "MEXC", status: "CONNECTED", latency_ms: 78, symbols_scanned: 220, rate_limit_percent: 34 },
  { exchange: "BYBIT", status: "CONNECTED", latency_ms: 55, symbols_scanned: 160, rate_limit_percent: 22 },
  { exchange: "OKX", status: "DEGRADED", latency_ms: 312, symbols_scanned: 140, rate_limit_percent: 85 },
];

// ─── Runner-Protection ─────────────────────────────────────────────
export const runnerPositions = [
  {
    id: "run_001",
    symbol: "XRPUSDT",
    exchange: "BINANCE",
    side: "LONG",
    entry_price: 0.6185,
    current_price: 0.6252,
    initial_stop_loss: 0.6120,
    current_trailing_stop: 0.6210,
    break_even_price: 0.6185,
    break_even_activated: true,
    tp1_price: 0.6240,
    tp2_price: 0.6280,
    tp3_price: 0.6350,
    tp1_filled: true,
    tp2_filled: false,
    tp3_filled: false,
    tp1_close_percent: 40,
    tp2_close_percent: 30,
    tp3_close_percent: 30,
    position_size: 5000,
    remaining_size_percent: 60,
    unrealized_pnl: 20.1,
    unrealized_pnl_percent: 1.08,
    volatility_atr_percent: 1.8,
    stop_adjustment_mode: "BREAK_EVEN",
    is_adopted: true,
    adoption_governance_approved: true,
    telegram_alert_sent: true,
    status: "TP1_HIT",
    opened_at: "2026-07-09T10:15:00Z",
    notes: "XRP Runner – TP1 getroffen, Stop auf BE, TP2 aktiv",
  },
  {
    id: "run_002",
    symbol: "SOLUSDT",
    exchange: "BINANCE",
    side: "LONG",
    entry_price: 146.2,
    current_price: 148.4,
    initial_stop_loss: 144.0,
    current_trailing_stop: 146.8,
    break_even_price: 146.2,
    break_even_activated: false,
    tp1_price: 148.0,
    tp2_price: 150.5,
    tp3_price: 154.0,
    tp1_filled: true,
    tp2_filled: false,
    tp3_filled: false,
    tp1_close_percent: 40,
    tp2_close_percent: 30,
    tp3_close_percent: 30,
    position_size: 50,
    remaining_size_percent: 60,
    unrealized_pnl: 66.0,
    unrealized_pnl_percent: 1.50,
    volatility_atr_percent: 2.4,
    stop_adjustment_mode: "ATR_BASED",
    is_adopted: true,
    adoption_governance_approved: true,
    telegram_alert_sent: true,
    status: "TP1_HIT",
    opened_at: "2026-07-09T09:30:00Z",
    notes: "SOL Runner – ATR-Stop aktiv, TP2 anvisiert",
  },
  {
    id: "run_003",
    symbol: "AVAXUSDT",
    exchange: "MEXC",
    side: "LONG",
    entry_price: 28.4,
    current_price: 29.1,
    initial_stop_loss: 27.8,
    current_trailing_stop: 28.2,
    break_even_price: 28.4,
    break_even_activated: false,
    tp1_price: 29.0,
    tp2_price: 29.8,
    tp3_price: 31.0,
    tp1_filled: false,
    tp2_filled: false,
    tp3_filled: false,
    tp1_close_percent: 40,
    tp2_close_percent: 30,
    tp3_close_percent: 30,
    position_size: 200,
    remaining_size_percent: 100,
    unrealized_pnl: 14.0,
    unrealized_pnl_percent: 2.46,
    volatility_atr_percent: 3.1,
    stop_adjustment_mode: "TIGHTENING",
    is_adopted: false,
    adoption_governance_approved: false,
    telegram_alert_sent: false,
    status: "PENDING_ADOPTION",
    opened_at: "2026-07-09T13:45:00Z",
    notes: "Adoption ausstehend – Governance-Freigabe erforderlich",
  },
];

export const runnerAuditLogs = [
  { id: "rul_001", action: "RUNNER_ADOPTED", symbol: "XRPUSDT", message: "XRP Runner adoptiert – Governance freigegeben", severity: "INFO", timestamp: "2026-07-09T10:15:05Z" },
  { id: "rul_002", action: "TP1_FILLED", symbol: "XRPUSDT", message: "TP1 @ 0.6240 – 40% geschlossen, Stop auf Break-Even", severity: "INFO", timestamp: "2026-07-09T11:42:00Z" },
  { id: "rul_003", action: "TRAILING_STOP_TIGHTENED", symbol: "XRPUSDT", message: "Trailing Stop von 0.6195 → 0.6210 (ATR-basiert)", severity: "INFO", timestamp: "2026-07-09T12:30:00Z" },
  { id: "rul_004", action: "VOLATILITY_ALERT", symbol: "AVAXUSDT", message: "ATR 3.1% – Stop-Anpassung empfohlen vor Adoption", severity: "WARNING", timestamp: "2026-07-09T13:45:00Z" },
  { id: "rul_005", action: "ADOPTION_PENDING", symbol: "AVAXUSDT", message: "Runner-Adoption wartet auf Governance-Freigabe", severity: "WARNING", timestamp: "2026-07-09T13:45:10Z" },
  { id: "rul_006", action: "TELEGRAM_ALERT_SENT", symbol: "XRPUSDT", message: "TP1 Hit Alert an Telegram gesendet", severity: "INFO", timestamp: "2026-07-09T11:42:05Z" },
];

// ─── Reverse-Short Playbook ───────────────────────────────────────
export const reverseShortSignals = [
  {
    id: "rsh_001",
    symbol: "ETHUSDT",
    exchange: "BINANCE",
    ascan_score: 84,
    rr: 3.5,
    reversal_type: "LIQUIDITY_SWEEP_REVERSAL",
    liquidity_sweep_detected: true,
    sweep_direction: "UPWARD_SWEEP",
    volume_confirmation: true,
    htf_bias: "SHORT",
    entry_price: 3152.0,
    stop_loss: 3188.0,
    tp1_price: 3105.0,
    tp2_price: 3060.0,
    tp3_runner_price: 2980.0,
    trailing_stop_active: false,
    trailing_stop_distance_percent: 1.2,
    decision: "ENTER_SHORT",
    runner_exit_strategy: "TRAILING_RUNNER",
    governance_approved: false,
    status: "GOVERNANCE_PENDING",
    notes: "Liquidity Sweep über H4 High + Rejection – klassischer Short Reversal",
    created_date: "2026-07-09T14:10:00Z",
  },
  {
    id: "rsh_002",
    symbol: "BTCUSDT",
    exchange: "BINANCE",
    ascan_score: 76,
    rr: 2.9,
    reversal_type: "FAKEOUT_REVERSAL",
    liquidity_sweep_detected: true,
    sweep_direction: "UPWARD_SWEEP",
    volume_confirmation: true,
    htf_bias: "NEUTRAL",
    entry_price: 61480.0,
    stop_loss: 61900.0,
    tp1_price: 60950.0,
    tp2_price: 60400.0,
    tp3_runner_price: 59200.0,
    trailing_stop_active: false,
    trailing_stop_distance_percent: 1.0,
    decision: "ENTER_SHORT_REDUCED",
    runner_exit_strategy: "PARTIAL_RUNNER",
    governance_approved: false,
    status: "VALIDATED",
    notes: "HTF nur partiell – reduzierte Position empfohlen",
    created_date: "2026-07-09T13:40:00Z",
  },
  {
    id: "rsh_003",
    symbol: "SOLUSDT",
    exchange: "MEXC",
    ascan_score: 58,
    rr: 1.8,
    reversal_type: "EXHAUSTION_REVERSAL",
    liquidity_sweep_detected: false,
    sweep_direction: "NONE",
    volume_confirmation: false,
    htf_bias: "NEUTRAL",
    entry_price: 148.5,
    stop_loss: 150.2,
    tp1_price: 146.0,
    tp2_price: 143.0,
    tp3_runner_price: 138.0,
    trailing_stop_active: false,
    trailing_stop_distance_percent: 1.5,
    decision: "WATCH_ONLY",
    runner_exit_strategy: "FULL_EXIT_TP3",
    governance_approved: false,
    status: "DETECTED",
    notes: "Sweep fehlt, Volume fehlt – WATCH_ONLY bis Bestätigung",
    created_date: "2026-07-09T13:00:00Z",
  },
  {
    id: "rsh_004",
    symbol: "DOGEUSDT",
    exchange: "BINANCE",
    ascan_score: 41,
    rr: 1.2,
    reversal_type: "DOUBLE_TOP_REVERSAL",
    liquidity_sweep_detected: false,
    sweep_direction: "NONE",
    volume_confirmation: false,
    htf_bias: "LONG",
    entry_price: 0,
    stop_loss: 0,
    tp1_price: 0,
    tp2_price: 0,
    tp3_runner_price: 0,
    trailing_stop_active: false,
    trailing_stop_distance_percent: 0,
    decision: "NO_TRADE",
    runner_exit_strategy: "FULL_EXIT_TP3",
    governance_approved: false,
    status: "DETECTED",
    notes: "Kein valides Reversal – HTF LONG, kein Short Setup",
    created_date: "2026-07-09T12:15:00Z",
  },
];

export const reverseShortPlaybook = [
  { id: "pb_001", pattern: "Liquidity Sweep Reversal", trigger: "Sweep über Key Level + Rejection Candle", min_score: 75, min_rr: 2.5, exit: "Trailing Runner", active: true },
  { id: "pb_002", pattern: "Fakeout Reversal", trigger: "False Breakout + Volume Drop + Reclaim", min_score: 70, min_rr: 2.0, exit: "Partial Runner", active: true },
  { id: "pb_003", pattern: "HTF Rejection Reversal", trigger: "D1/W1 Level Reject + LTF Confirmation", min_score: 78, min_rr: 3.0, exit: "Trailing Runner", active: true },
  { id: "pb_004", pattern: "Exhaustion Reversal", trigger: "3+ Pushes + Divergence + Sweep", min_score: 72, min_rr: 2.5, exit: "Break-Even Runner", active: true },
  { id: "pb_005", pattern: "Double Top Reversal", trigger: "Equal Highs + Lower High + Volume Confirm", min_score: 68, min_rr: 2.0, exit: "Full Exit TP3", active: false },
];

// ─── Governance Action Types (erweitert) ───────────────────────────
export const governanceActionLabelsExtended = {
  LIVE_TRADE: "Live Trade",
  PAPER_TO_LIVE: "Paper → Live",
  RISK_INCREASE: "Risiko-Erhöhung",
  LEVERAGE_INCREASE: "Leverage-Erhöhung",
  EXCHANGE_KEY_ACTIVATION: "API-Key Aktivierung",
  DISABLE_STOP_LOSS: "Stop-Loss deaktivieren",
  MAX_POSITIONS_INCREASE: "Max. Positionen erhöhen",
  STRATEGY_SWITCH: "Strategie wechseln",
  EMERGENCY_OVERRIDE: "Emergency Override",
  PROXY_SWITCH: "Proxy-Wechsel",
  RUNNER_ADOPTION: "Runner-Adoption",
  ARB_EXECUTION: "ARB-Ausführung",
  REVERSE_SHORT_EXECUTION: "Reverse-Short Ausführung",
  SAFETY_DEACTIVATION: "Schutz deaktivieren",
};

export const arbStatusMeta = {
  DETECTED: { color: "muted", label: "Erkannt" },
  ALERTED: { color: "cyan", label: "Alerted" },
  GOVERNANCE_PENDING: { color: "warning", label: "Freigabe ausstehend" },
  APPROVED: { color: "profit", label: "Freigegeben" },
  EXECUTED: { color: "profit", label: "Ausgeführt" },
  EXPIRED: { color: "muted", label: "Abgelaufen" },
  REJECTED: { color: "loss", label: "Abgelehnt" },
};

export const regimeMeta = {
  CALM: { color: "profit", desc: "Stabil, niedrige Volatilität" },
  VOLATILE: { color: "warning", desc: "Hohe Volatilität, Vorsicht" },
  TRENDING: { color: "cyan", desc: "Gerichteter Trend" },
  ILLIQUID: { color: "loss", desc: "Geringe Liquidität, Slippage-Risiko" },
  EXTREME: { color: "loss", desc: "Extreme Bedingungen, Trading pausieren" },
};

export const runnerStatusMeta = {
  PENDING_ADOPTION: { color: "warning", label: "Adoption ausstehend" },
  ACTIVE: { color: "cyan", label: "Aktiv" },
  TP1_HIT: { color: "profit", label: "TP1 getroffen" },
  TP2_HIT: { color: "profit", label: "TP2 getroffen" },
  RUNNER_ACTIVE: { color: "profit", label: "Runner aktiv" },
  CLOSED: { color: "muted", label: "Geschlossen" },
  STOPPED_OUT: { color: "loss", label: "Gestoppt" },
  BREAKEVEN: { color: "cyan", label: "Break-Even" },
};

export const reversalTypeMeta = {
  LIQUIDITY_SWEEP_REVERSAL: { color: "loss", label: "Liquidity Sweep Reversal" },
  FAKEOUT_REVERSAL: { color: "warning", label: "Fakeout Reversal" },
  HTF_REJECTION_REVERSAL: { color: "loss", label: "HTF Rejection Reversal" },
  EXHAUSTION_REVERSAL: { color: "warning", label: "Exhaustion Reversal" },
  DOUBLE_TOP_REVERSAL: { color: "muted", label: "Double Top Reversal" },
};

export const shortDecisionMeta = {
  ENTER_SHORT: { color: "profit", label: "ENTER SHORT" },
  ENTER_SHORT_REDUCED: { color: "cyan", label: "ENTER SHORT (reduziert)" },
  WATCH_ONLY: { color: "warning", label: "WATCH ONLY" },
  NO_TRADE: { color: "loss", label: "NO TRADE" },
};